const indianStates = [
  { value: "Andhra Pradesh", label: "Andhra Pradesh" },
  { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
  { value: "Assam", label: "Assam" },
  { value: "Bihar", label: "Bihar" },
  { value: "Chhattisgarh", label: "Chhattisgarh" },
  { value: "Goa", label: "Goa" },
  { value: "Gujarat", label: "Gujarat" },
  { value: "Haryana", label: "Haryana" },
  { value: "Himachal Pradesh", label: "Himachal Pradesh" },
  { value: "Jharkhand", label: "Jharkhand" },
  { value: "Karnataka", label: "Karnataka" },
  { value: "Kerala", label: "Kerala" },
  { value: "MP", label: "Madhya Pradesh" },
  { value: "Maharashtra", label: "Maharashtra" },
  { value: "Manipur", label: "Manipur" },
  { value: "Meghalaya", label: "Meghalaya" },
  { value: "Mizoram", label: "Mizoram" },
  { value: "Nagaland", label: "Nagaland" },
  { value: "Odisha", label: "Odisha" },
  { value: "Punjab", label: "Punjab" },
  { value: "Rajasthan", label: "Rajasthan" },
  { value: "Sikkim", label: "Sikkim" },
  { value: "Tamil Nadu", label: "Tamil Nadu" },
  { value: "Telangana", label: "Telangana" },
  { value: "Tripura", label: "Tripura" },
  { value: "UP", label: "Uttar Pradesh" },
  { value: "Uttarakhand", label: "Uttarakhand" },
  { value: "West Bengal", label: "West Bengal" },
  {
    value: "Andaman and Nicobar Islands",
    label: "Andaman and Nicobar Islands",
  },
  { value: "Chandigarh", label: "Chandigarh" },
  {
    value: "Dadra and Nagar Haveli and Daman and Diu",
    label: "Dadra and Nagar Haveli and Daman and Diu",
  },
  { value: "Lakshadweep", label: "Lakshadweep" },
  { value: "Delhi", label: "Delhi" },
  { value: "Puducherry", label: "Puducherry" },
  { value: "Ladakh", label: "Ladakh" },
  { value: "Jammu and Kashmir", label: "Jammu and Kashmir" },
];

const andhraPradeshDistricts = [
  { value: "Anantapur", label: "Anantapur" },
  { value: "Chittoor", label: "Chittoor" },
  { value: "East Godavari", label: "East Godavari" },
  { value: "Guntur", label: "Guntur" },
  { value: "Kadapa", label: "Kadapa" },
  { value: "Krishna", label: "Krishna" },
  { value: "Kurnool", label: "Kurnool" },
  { value: "Nellore", label: "Nellore" },
  { value: "Prakasam", label: "Prakasam" },
  { value: "Srikakulam", label: "Srikakulam" },
  { value: "Visakhapatnam", label: "Visakhapatnam" },
  { value: "Vizianagaram", label: "Vizianagaram" },
  { value: "West Godavari", label: "West Godavari" },
];

const arunachalPradeshDistricts = [
  { value: "Anjaw", label: "Anjaw" },
  { value: "Changlang", label: "Changlang" },
  { value: "Dibang Valley", label: "Dibang Valley" },
  { value: "East Kameng", label: "East Kameng" },
  { value: "East Siang", label: "East Siang" },
  { value: "Kamle", label: "Kamle" },
  { value: "Kra Daadi", label: "Kra Daadi" },
  { value: "Kurung Kumey", label: "Kurung Kumey" },
  { value: "Lepa Rada", label: "Lepa Rada" },
  { value: "Lohit", label: "Lohit" },
  { value: "Longding", label: "Longding" },
  { value: "Lower Dibang Valley", label: "Lower Dibang Valley" },
  { value: "Lower Siang", label: "Lower Siang" },
  { value: "Lower Subansiri", label: "Lower Subansiri" },
  { value: "Namsai", label: "Namsai" },
  { value: "Pakke-Kessang", label: "Pakke-Kessang" },
  { value: "Papum Pare", label: "Papum Pare" },
  { value: "Shi Yomi", label: "Shi Yomi" },
  { value: "Siang", label: "Siang" },
  { value: "Tawang", label: "Tawang" },
  { value: "Tirap", label: "Tirap" },
  { value: "Upper Siang", label: "Upper Siang" },
  { value: "Upper Subansiri", label: "Upper Subansiri" },
  { value: "West Kameng", label: "West Kameng" },
  { value: "West Siang", label: "West Siang" },
];

const assamDistricts = [
  { value: "Baksa", label: "Baksa" },
  { value: "Barpeta", label: "Barpeta" },
  { value: "Biswanath", label: "Biswanath" },
  { value: "Bongaigaon", label: "Bongaigaon" },
  { value: "Cachar", label: "Cachar" },
  { value: "Charaideo", label: "Charaideo" },
  { value: "Chirang", label: "Chirang" },
  { value: "Darrang", label: "Darrang" },
  { value: "Dhemaji", label: "Dhemaji" },
  { value: "Dhubri", label: "Dhubri" },
  { value: "Dibrugarh", label: "Dibrugarh" },
  { value: "Dima Hasao", label: "Dima Hasao" },
  { value: "Goalpara", label: "Goalpara" },
  { value: "Golaghat", label: "Golaghat" },
  { value: "Hailakandi", label: "Hailakandi" },
  { value: "Hojai", label: "Hojai" },
  { value: "Jorhat", label: "Jorhat" },
  { value: "Kamrup", label: "Kamrup" },
  { value: "Kamrup Metropolitan", label: "Kamrup Metropolitan" },
  { value: "Karbi Anglong", label: "Karbi Anglong" },
  { value: "Karimganj", label: "Karimganj" },
  { value: "Kokrajhar", label: "Kokrajhar" },
  { value: "Lakhimpur", label: "Lakhimpur" },
  { value: "Majuli", label: "Majuli" },
  { value: "Morigaon", label: "Morigaon" },
  { value: "Nagaon", label: "Nagaon" },
  { value: "Nalbari", label: "Nalbari" },
  { value: "Sivasagar", label: "Sivasagar" },
  { value: "Sonitpur", label: "Sonitpur" },
  { value: "South Salmara-Mankachar", label: "South Salmara-Mankachar" },
  { value: "Tinsukia", label: "Tinsukia" },
  { value: "Udalguri", label: "Udalguri" },
  { value: "West Karbi Anglong", label: "West Karbi Anglong" },
];

const biharDistricts = [
  { value: "Araria", label: "Araria" },
  { value: "Arwal", label: "Arwal" },
  { value: "Aurangabad", label: "Aurangabad" },
  { value: "Banka", label: "Banka" },
  { value: "Begusarai", label: "Begusarai" },
  { value: "Bhagalpur", label: "Bhagalpur" },
  { value: "Bhojpur", label: "Bhojpur" },
  { value: "Buxar", label: "Buxar" },
  { value: "Darbhanga", label: "Darbhanga" },
  { value: "East Champaran", label: "East Champaran" },
  { value: "Gaya", label: "Gaya" },
  { value: "Gopalganj", label: "Gopalganj" },
  { value: "Jamui", label: "Jamui" },
  { value: "Jehanabad", label: "Jehanabad" },
  { value: "Kaimur", label: "Kaimur" },
  { value: "Katihar", label: "Katihar" },
  { value: "Khagaria", label: "Khagaria" },
  { value: "Kishanganj", label: "Kishanganj" },
  { value: "Lakhisarai", label: "Lakhisarai" },
  { value: "Madhepura", label: "Madhepura" },
  { value: "Madhubani", label: "Madhubani" },
  { value: "Munger", label: "Munger" },
  { value: "Muzaffarpur", label: "Muzaffarpur" },
  { value: "Nalanda", label: "Nalanda" },
  { value: "Nawada", label: "Nawada" },
  { value: "Patna", label: "Patna" },
  { value: "Purnia", label: "Purnia" },
  { value: "Rohtas", label: "Rohtas" },
  { value: "Saharsa", label: "Saharsa" },
  { value: "Samastipur", label: "Samastipur" },
  { value: "Saran", label: "Saran" },
  { value: "Sheikhpura", label: "Sheikhpura" },
  { value: "Sheohar", label: "Sheohar" },
  { value: "Sitamarhi", label: "Sitamarhi" },
  { value: "Siwan", label: "Siwan" },
  { value: "Supaul", label: "Supaul" },
  { value: "Vaishali", label: "Vaishali" },
  { value: "West Champaran", label: "West Champaran" },
];

const chhattisgarhDistricts = [
  { value: "Balod", label: "Balod" },
  { value: "Baloda Bazar", label: "Baloda Bazar" },
  { value: "Balrampur", label: "Balrampur" },
  { value: "Bastar", label: "Bastar" },
  { value: "Bemetara", label: "Bemetara" },
  { value: "Bijapur", label: "Bijapur" },
  { value: "Bilaspur", label: "Bilaspur" },
  { value: "Dantewada", label: "Dantewada" },
  { value: "Dhamtari", label: "Dhamtari" },
  { value: "Durg", label: "Durg" },
  { value: "Gariaband", label: "Gariaband" },
  { value: "Gaurela-Pendra-Marwahi", label: "Gaurela-Pendra-Marwahi" },
  { value: "Janjgir-Champa", label: "Janjgir-Champa" },
  { value: "Jashpur", label: "Jashpur" },
  { value: "Kabirdham", label: "Kabirdham" },
  { value: "Kanker", label: "Kanker" },
  { value: "Kondagaon", label: "Kondagaon" },
  { value: "Korba", label: "Korba" },
  { value: "Koriya", label: "Koriya" },
  { value: "Mahasamund", label: "Mahasamund" },
  { value: "Mungeli", label: "Mungeli" },
  { value: "Narayanpur", label: "Narayanpur" },
  { value: "Raigarh", label: "Raigarh" },
  { value: "Raipur", label: "Raipur" },
  { value: "Rajnandgaon", label: "Rajnandgaon" },
  { value: "Sukma", label: "Sukma" },
  { value: "Surajpur", label: "Surajpur" },
  { value: "Surguja", label: "Surguja" },
];

const goaDistricts = [
  { value: "North Goa", label: "North Goa" },
  { value: "South Goa", label: "South Goa" },
];

const gujaratDistricts = [
  { value: "Ahmedabad", label: "Ahmedabad" },
  { value: "Amreli", label: "Amreli" },
  { value: "Anand", label: "Anand" },
  { value: "Aravalli", label: "Aravalli" },
  { value: "Banaskantha", label: "Banaskantha" },
  { value: "Bharuch", label: "Bharuch" },
  { value: "Bhavnagar", label: "Bhavnagar" },
  { value: "Botad", label: "Botad" },
  { value: "Chhota Udaipur", label: "Chhota Udaipur" },
  { value: "Dahod", label: "Dahod" },
  { value: "Dang", label: "Dang" },
  { value: "Devbhoomi Dwarka", label: "Devbhoomi Dwarka" },
  { value: "Gandhinagar", label: "Gandhinagar" },
  { value: "Gir Somnath", label: "Gir Somnath" },
  { value: "Jamnagar", label: "Jamnagar" },
  { value: "Junagadh", label: "Junagadh" },
  { value: "Kheda", label: "Kheda" },
  { value: "Kutch", label: "Kutch" },
  { value: "Mahisagar", label: "Mahisagar" },
  { value: "Mehsana", label: "Mehsana" },
  { value: "Morbi", label: "Morbi" },
  { value: "Narmada", label: "Narmada" },
  { value: "Navsari", label: "Navsari" },
  { value: "Panchmahal", label: "Panchmahal" },
  { value: "Patan", label: "Patan" },
  { value: "Porbandar", label: "Porbandar" },
  { value: "Rajkot", label: "Rajkot" },
  { value: "Sabarkantha", label: "Sabarkantha" },
  { value: "Surat", label: "Surat" },
  { value: "Surendranagar", label: "Surendranagar" },
  { value: "Tapi", label: "Tapi" },
  { value: "Vadodara", label: "Vadodara" },
  { value: "Valsad", label: "Valsad" },
];

const haryanaDistricts = [
  { value: "Ambala", label: "Ambala" },
  { value: "Bhiwani", label: "Bhiwani" },
  { value: "Charkhi Dadri", label: "Charkhi Dadri" },
  { value: "Faridabad", label: "Faridabad" },
  { value: "Fatehabad", label: "Fatehabad" },
  { value: "Gurugram", label: "Gurugram" },
  { value: "Hisar", label: "Hisar" },
  { value: "Jhajjar", label: "Jhajjar" },
  { value: "Jind", label: "Jind" },
  { value: "Kaithal", label: "Kaithal" },
  { value: "Karnal", label: "Karnal" },
  { value: "Kurukshetra", label: "Kurukshetra" },
  { value: "Mahendragarh", label: "Mahendragarh" },
  { value: "Nuh", label: "Nuh" },
  { value: "Palwal", label: "Palwal" },
  { value: "Panchkula", label: "Panchkula" },
  { value: "Panipat", label: "Panipat" },
  { value: "Rewari", label: "Rewari" },
  { value: "Rohtak", label: "Rohtak" },
  { value: "Sirsa", label: "Sirsa" },
  { value: "Sonipat", label: "Sonipat" },
  { value: "Yamunanagar", label: "Yamunanagar" },
];

const himachalPradeshDistricts = [
  { value: "Bilaspur", label: "Bilaspur" },
  { value: "Chamba", label: "Chamba" },
  { value: "Hamirpur", label: "Hamirpur" },
  { value: "Kangra", label: "Kangra" },
  { value: "Kinnaur", label: "Kinnaur" },
  { value: "Kullu", label: "Kullu" },
  { value: "Lahaul and Spiti", label: "Lahaul and Spiti" },
  { value: "Mandi", label: "Mandi" },
  { value: "Shimla", label: "Shimla" },
  { value: "Sirmaur", label: "Sirmaur" },
  { value: "Solan", label: "Solan" },
  { value: "Una", label: "Una" },
];

const jharkhandDistricts = [
  { value: "Bokaro", label: "Bokaro" },
  { value: "Chatra", label: "Chatra" },
  { value: "Deoghar", label: "Deoghar" },
  { value: "Dhanbad", label: "Dhanbad" },
  { value: "Dumka", label: "Dumka" },
  { value: "East Singhbhum", label: "East Singhbhum" },
  { value: "Garhwa", label: "Garhwa" },
  { value: "Giridih", label: "Giridih" },
  { value: "Godda", label: "Godda" },
  { value: "Gumla", label: "Gumla" },
  { value: "Hazaribagh", label: "Hazaribagh" },
  { value: "Jamtara", label: "Jamtara" },
  { value: "Khunti", label: "Khunti" },
  { value: "Koderma", label: "Koderma" },
  { value: "Latehar", label: "Latehar" },
  { value: "Lohardaga", label: "Lohardaga" },
  { value: "Pakur", label: "Pakur" },
  { value: "Palamu", label: "Palamu" },
  { value: "Ramgarh", label: "Ramgarh" },
  { value: "Ranchi", label: "Ranchi" },
  { value: "Sahebganj", label: "Sahebganj" },
  { value: "Seraikela Kharsawan", label: "Seraikela Kharsawan" },
  { value: "Simdega", label: "Simdega" },
  { value: "West Singhbhum", label: "West Singhbhum" },
];

const karnatakaDistricts = [
  { value: "Bagalkot", label: "Bagalkot" },
  { value: "Ballari", label: "Ballari" },
  { value: "Belagavi", label: "Belagavi" },
  { value: "Bengaluru Rural", label: "Bengaluru Rural" },
  { value: "Bengaluru Urban", label: "Bengaluru Urban" },
  { value: "Bidar", label: "Bidar" },
  { value: "Chamarajanagar", label: "Chamarajanagar" },
  { value: "Chikballapur", label: "Chikballapur" },
  { value: "Chikkamagaluru", label: "Chikkamagaluru" },
  { value: "Chitradurga", label: "Chitradurga" },
  { value: "Dakshina Kannada", label: "Dakshina Kannada" },
  { value: "Davanagere", label: "Davanagere" },
  { value: "Dharwad", label: "Dharwad" },
  { value: "Gadag", label: "Gadag" },
  { value: "Hassan", label: "Hassan" },
  { value: "Haveri", label: "Haveri" },
  { value: "Kalaburagi", label: "Kalaburagi" },
  { value: "Kodagu", label: "Kodagu" },
  { value: "Kolar", label: "Kolar" },
  { value: "Koppal", label: "Koppal" },
  { value: "Mandya", label: "Mandya" },
  { value: "Mysuru", label: "Mysuru" },
  { value: "Raichur", label: "Raichur" },
  { value: "Ramanagara", label: "Ramanagara" },
  { value: "Shivamogga", label: "Shivamogga" },
  { value: "Tumakuru", label: "Tumakuru" },
  { value: "Udupi", label: "Udupi" },
  { value: "Uttara Kannada", label: "Uttara Kannada" },
  { value: "Vijayapura", label: "Vijayapura" },
  { value: "Yadgir", label: "Yadgir" },
];

const keralaDistricts = [
  { value: "Alappuzha", label: "Alappuzha" },
  { value: "Ernakulam", label: "Ernakulam" },
  { value: "Idukki", label: "Idukki" },
  { value: "Kannur", label: "Kannur" },
  { value: "Kasaragod", label: "Kasaragod" },
  { value: "Kollam", label: "Kollam" },
  { value: "Kottayam", label: "Kottayam" },
  { value: "Kozhikode", label: "Kozhikode" },
  { value: "Malappuram", label: "Malappuram" },
  { value: "Palakkad", label: "Palakkad" },
  { value: "Pathanamthitta", label: "Pathanamthitta" },
  { value: "Thiruvananthapuram", label: "Thiruvananthapuram" },
  { value: "Thrissur", label: "Thrissur" },
  { value: "Wayanad", label: "Wayanad" },
];

const maharashtraDistricts = [
  { value: "Ahmednagar", label: "Ahmednagar" },
  { value: "Akola", label: "Akola" },
  { value: "Amravati", label: "Amravati" },
  { value: "Aurangabad", label: "Aurangabad" },
  { value: "Beed", label: "Beed" },
  { value: "Bhandara", label: "Bhandara" },
  { value: "Buldhana", label: "Buldhana" },
  { value: "Chandrapur", label: "Chandrapur" },
  { value: "Dhule", label: "Dhule" },
  { value: "Gadchiroli", label: "Gadchiroli" },
  { value: "Gondia", label: "Gondia" },
  { value: "Hingoli", label: "Hingoli" },
  { value: "Jalgaon", label: "Jalgaon" },
  { value: "Jalna", label: "Jalna" },
  { value: "Kolhapur", label: "Kolhapur" },
  { value: "Latur", label: "Latur" },
  { value: "Mumbai City", label: "Mumbai City" },
  { value: "Mumbai Suburban", label: "Mumbai Suburban" },
  { value: "Nagpur", label: "Nagpur" },
  { value: "Nanded", label: "Nanded" },
  { value: "Nandurbar", label: "Nandurbar" },
  { value: "Nashik", label: "Nashik" },
  { value: "Osmanabad", label: "Osmanabad" },
  { value: "Palghar", label: "Palghar" },
  { value: "Parbhani", label: "Parbhani" },
  { value: "Pune", label: "Pune" },
  { value: "Raigad", label: "Raigad" },
  { value: "Ratnagiri", label: "Ratnagiri" },
  { value: "Sangli", label: "Sangli" },
  { value: "Satara", label: "Satara" },
  { value: "Sindhudurg", label: "Sindhudurg" },
  { value: "Solapur", label: "Solapur" },
  { value: "Thane", label: "Thane" },
  { value: "Wardha", label: "Wardha" },
  { value: "Washim", label: "Washim" },
  { value: "Yavatmal", label: "Yavatmal" },
];

const manipurDistricts = [
  { value: "Bishnupur", label: "Bishnupur" },
  { value: "Chandel", label: "Chandel" },
  { value: "Churachandpur", label: "Churachandpur" },
  { value: "Imphal East", label: "Imphal East" },
  { value: "Imphal West", label: "Imphal West" },
  { value: "Jiribam", label: "Jiribam" },
  { value: "Kakching", label: "Kakching" },
  { value: "Kamjong", label: "Kamjong" },
  { value: "Kangpokpi", label: "Kangpokpi" },
  { value: "Noney", label: "Noney" },
  { value: "Pherzawl", label: "Pherzawl" },
  { value: "Senapati", label: "Senapati" },
  { value: "Tamenglong", label: "Tamenglong" },
  { value: "Tengnoupal", label: "Tengnoupal" },
  { value: "Thoubal", label: "Thoubal" },
  { value: "Ukhrul", label: "Ukhrul" },
];

const meghalayaDistricts = [
  { value: "East Garo Hills", label: "East Garo Hills" },
  { value: "East Jaintia Hills", label: "East Jaintia Hills" },
  { value: "East Khasi Hills", label: "East Khasi Hills" },
  { value: "North Garo Hills", label: "North Garo Hills" },
  { value: "Ri Bhoi", label: "Ri Bhoi" },
  { value: "South Garo Hills", label: "South Garo Hills" },
  { value: "South West Garo Hills", label: "South West Garo Hills" },
  { value: "South West Khasi Hills", label: "South West Khasi Hills" },
  { value: "West Garo Hills", label: "West Garo Hills" },
  { value: "West Jaintia Hills", label: "West Jaintia Hills" },
  { value: "West Khasi Hills", label: "West Khasi Hills" },
];

const mizoramDistricts = [
  { value: "Aizawl", label: "Aizawl" },
  { value: "Champhai", label: "Champhai" },
  { value: "Hnahthial", label: "Hnahthial" },
  { value: "Khawzawl", label: "Khawzawl" },
  { value: "Kolasib", label: "Kolasib" },
  { value: "Lawngtlai", label: "Lawngtlai" },
  { value: "Lunglei", label: "Lunglei" },
  { value: "Mamit", label: "Mamit" },
  { value: "Saiha", label: "Saiha" },
  { value: "Saitual", label: "Saitual" },
  { value: "Serchhip", label: "Serchhip" },
];

const nagalandDistricts = [
  { value: "Chümoukedima", label: "Chümoukedima" },
  { value: "Dimapur", label: "Dimapur" },
  { value: "Kiphire", label: "Kiphire" },
  { value: "Kohima", label: "Kohima" },
  { value: "Longleng", label: "Longleng" },
  { value: "Mokokchung", label: "Mokokchung" },
  { value: "Mon", label: "Mon" },
  { value: "Noklak", label: "Noklak" },
  { value: "Peren", label: "Peren" },
  { value: "Phek", label: "Phek" },
  { value: "Tuensang", label: "Tuensang" },
  { value: "Tseminyu", label: "Tseminyu" },
  { value: "Wokha", label: "Wokha" },
  { value: "Zünheboto", label: "Zünheboto" },
];

const odishaDistricts = [
  { value: "Angul", label: "Angul" },
  { value: "Balangir", label: "Balangir" },
  { value: "Balasore", label: "Balasore" },
  { value: "Bargarh", label: "Bargarh" },
  { value: "Bhadrak", label: "Bhadrak" },
  { value: "Boudh", label: "Boudh" },
  { value: "Cuttack", label: "Cuttack" },
  { value: "Deogarh", label: "Deogarh" },
  { value: "Dhenkanal", label: "Dhenkanal" },
  { value: "Gajapati", label: "Gajapati" },
  { value: "Ganjam", label: "Ganjam" },
  { value: "Jagatsinghpur", label: "Jagatsinghpur" },
  { value: "Jajpur", label: "Jajpur" },
  { value: "Jharsuguda", label: "Jharsuguda" },
  { value: "Kalahandi", label: "Kalahandi" },
  { value: "Kandhamal", label: "Kandhamal" },
  { value: "Kendrapara", label: "Kendrapara" },
  { value: "Kendujhar (Keonjhar)", label: "Kendujhar (Keonjhar)" },
  { value: "Khordha", label: "Khordha" },
  { value: "Koraput", label: "Koraput" },
  { value: "Malkangiri", label: "Malkangiri" },
  { value: "Mayurbhanj", label: "Mayurbhanj" },
  { value: "Nabarangpur", label: "Nabarangpur" },
  { value: "Nayagarh", label: "Nayagarh" },
  { value: "Nuapada", label: "Nuapada" },
  { value: "Puri", label: "Puri" },
  { value: "Rayagada", label: "Rayagada" },
  { value: "Sambalpur", label: "Sambalpur" },
  { value: "Sonepur", label: "Sonepur" },
  { value: "Sundargarh", label: "Sundargarh" },
];

const punjabDistricts = [
  { value: "Amritsar", label: "Amritsar" },
  { value: "Barnala", label: "Barnala" },
  { value: "Bathinda", label: "Bathinda" },
  { value: "Faridkot", label: "Faridkot" },
  { value: "Fatehgarh Sahib", label: "Fatehgarh Sahib" },
  { value: "Fazilka", label: "Fazilka" },
  { value: "Ferozepur", label: "Ferozepur" },
  { value: "Gurdaspur", label: "Gurdaspur" },
  { value: "Hoshiarpur", label: "Hoshiarpur" },
  { value: "Jalandhar", label: "Jalandhar" },
  { value: "Kapurthala", label: "Kapurthala" },
  { value: "Ludhiana", label: "Ludhiana" },
  { value: "Mansa", label: "Mansa" },
  { value: "Moga", label: "Moga" },
  { value: "Muktsar", label: "Muktsar" },
  {
    value: "Nawanshahr (Shahid Bhagat Singh Nagar)",
    label: "Nawanshahr (Shahid Bhagat Singh Nagar)",
  },
  { value: "Pathankot", label: "Pathankot" },
  { value: "Patiala", label: "Patiala" },
  { value: "Rupnagar", label: "Rupnagar" },
  { value: "Sangrur", label: "Sangrur" },
  { value: "SAS Nagar (Mohali)", label: "SAS Nagar (Mohali)" },
  { value: "Tarn Taran", label: "Tarn Taran" },
];

const sikkimDistricts = [
  { value: "East Sikkim", label: "East Sikkim" },
  { value: "North Sikkim", label: "North Sikkim" },
  { value: "South Sikkim", label: "South Sikkim" },
  { value: "West Sikkim", label: "West Sikkim" },
];

const tamilNaduDistricts = [
  { value: "Ariyalur", label: "Ariyalur" },
  { value: "Chengalpattu", label: "Chengalpattu" },
  { value: "Chennai", label: "Chennai" },
  { value: "Coimbatore", label: "Coimbatore" },
  { value: "Cuddalore", label: "Cuddalore" },
  { value: "Dharmapuri", label: "Dharmapuri" },
  { value: "Dindigul", label: "Dindigul" },
  { value: "Erode", label: "Erode" },
  { value: "Kallakurichi", label: "Kallakurichi" },
  { value: "Kancheepuram", label: "Kancheepuram" },
  { value: "Karur", label: "Karur" },
  { value: "Krishnagiri", label: "Krishnagiri" },
  { value: "Madurai", label: "Madurai" },
  { value: "Nagapattinam", label: "Nagapattinam" },
  { value: "Namakkal", label: "Namakkal" },
  { value: "Nilgiris", label: "Nilgiris" },
  { value: "Perambalur", label: "Perambalur" },
  { value: "Pudukkottai", label: "Pudukkottai" },
  { value: "Ramanathapuram", label: "Ramanathapuram" },
  { value: "Ranipet", label: "Ranipet" },
  { value: "Salem", label: "Salem" },
  { value: "Sivaganga", label: "Sivaganga" },
  { value: "Tenkasi", label: "Tenkasi" },
  { value: "Thanjavur", label: "Thanjavur" },
  { value: "Theni", label: "Theni" },
  { value: "Thoothukudi", label: "Thoothukudi" },
  { value: "Tiruchirappalli", label: "Tiruchirappalli" },
  { value: "Tirunelveli", label: "Tirunelveli" },
  { value: "Tirupathur", label: "Tirupathur" },
  { value: "Tiruppur", label: "Tiruppur" },
  { value: "Tiruvallur", label: "Tiruvallur" },
  { value: "Tiruvannamalai", label: "Tiruvannamalai" },
  { value: "Tiruvarur", label: "Tiruvarur" },
  { value: "Vellore", label: "Vellore" },
  { value: "Viluppuram", label: "Viluppuram" },
  { value: "Virudhunagar", label: "Virudhunagar" },
];

const telanganaDistricts = [
  { value: "Adilabad", label: "Adilabad" },
  { value: "Bhadradri Kothagudem", label: "Bhadradri Kothagudem" },
  { value: "Hyderabad", label: "Hyderabad" },
  { value: "Jagtial", label: "Jagtial" },
  { value: "Jangaon", label: "Jangaon" },
  { value: "Jayashankar Bhupalpally", label: "Jayashankar Bhupalpally" },
  { value: "Jogulamba Gadwal", label: "Jogulamba Gadwal" },
  { value: "Kamareddy", label: "Kamareddy" },
  { value: "Karimnagar", label: "Karimnagar" },
  { value: "Khammam", label: "Khammam" },
  { value: "Kumuram Bheem Asifabad", label: "Kumuram Bheem Asifabad" },
  { value: "Mahabubabad", label: "Mahabubabad" },
  { value: "Mahbubnagar", label: "Mahbubnagar" },
  { value: "Mancherial", label: "Mancherial" },
  { value: "Medak", label: "Medak" },
  { value: "Medchal-Malkajgiri", label: "Medchal-Malkajgiri" },
  { value: "Mulugu", label: "Mulugu" },
  { value: "Nagarkurnool", label: "Nagarkurnool" },
  { value: "Nalgonda", label: "Nalgonda" },
  { value: "Narayanpet", label: "Narayanpet" },
  { value: "Nirmal", label: "Nirmal" },
  { value: "Nizamabad", label: "Nizamabad" },
  { value: "Peddapalli", label: "Peddapalli" },
  { value: "Rajanna Sircilla", label: "Rajanna Sircilla" },
  { value: "Ranga Reddy", label: "Ranga Reddy" },
  { value: "Sangareddy", label: "Sangareddy" },
  { value: "Siddipet", label: "Siddipet" },
  { value: "Suryapet", label: "Suryapet" },
  { value: "Vikarabad", label: "Vikarabad" },
  { value: "Wanaparthy", label: "Wanaparthy" },
  { value: "Warangal Rural", label: "Warangal Rural" },
  { value: "Warangal Urban", label: "Warangal Urban" },
  { value: "Yadadri Bhuvanagiri", label: "Yadadri Bhuvanagiri" },
];

const tripuraDistricts = [
  { value: "Dhalai", label: "Dhalai" },
  { value: "Gomati", label: "Gomati" },
  { value: "Khowai", label: "Khowai" },
  { value: "North Tripura", label: "North Tripura" },
  { value: "Sepahijala", label: "Sepahijala" },
  { value: "South Tripura", label: "South Tripura" },
  { value: "Unakoti", label: "Unakoti" },
  { value: "West Tripura", label: "West Tripura" },
];

const uttarakhandDistricts = [
  { value: "Almora", label: "Almora" },
  { value: "Bageshwar", label: "Bageshwar" },
  { value: "Chamoli", label: "Chamoli" },
  { value: "Champawat", label: "Champawat" },
  { value: "Dehradun", label: "Dehradun" },
  { value: "Haridwar", label: "Haridwar" },
  { value: "Nainital", label: "Nainital" },
  { value: "Pauri Garhwal", label: "Pauri Garhwal" },
  { value: "Pithoragarh", label: "Pithoragarh" },
  { value: "Rudraprayag", label: "Rudraprayag" },
  { value: "Tehri Garhwal", label: "Tehri Garhwal" },
  { value: "Udham Singh Nagar", label: "Udham Singh Nagar" },
  { value: "Uttarkashi", label: "Uttarkashi" },
];

const westBengalDistricts = [
  { value: "Alipurduar", label: "Alipurduar" },
  { value: "Bankura", label: "Bankura" },
  { value: "Birbhum", label: "Birbhum" },
  { value: "Cooch Behar", label: "Cooch Behar" },
  { value: "Dakshin Dinajpur", label: "Dakshin Dinajpur" },
  { value: "Darjeeling", label: "Darjeeling" },
  { value: "Hooghly", label: "Hooghly" },
  { value: "Howrah", label: "Howrah" },
  { value: "Jalpaiguri", label: "Jalpaiguri" },
  { value: "Jhargram", label: "Jhargram" },
  { value: "Kalimpong", label: "Kalimpong" },
  { value: "Kolkata", label: "Kolkata" },
  { value: "Malda", label: "Malda" },
  { value: "Murshidabad", label: "Murshidabad" },
  { value: "Nadia", label: "Nadia" },
  { value: "North 24 Parganas", label: "North 24 Parganas" },
  { value: "Paschim Bardhaman", label: "Paschim Bardhaman" },
  { value: "Paschim Medinipur", label: "Paschim Medinipur" },
  { value: "Purba Bardhaman", label: "Purba Bardhaman" },
  { value: "Purba Medinipur", label: "Purba Medinipur" },
  { value: "Purulia", label: "Purulia" },
  { value: "South 24 Parganas", label: "South 24 Parganas" },
  { value: "Uttar Dinajpur", label: "Uttar Dinajpur" },
];

const andamanNicobarDistricts = [
  { value: "Nicobar", label: "Nicobar" },
  { value: "North and Middle Andaman", label: "North and Middle Andaman" },
  { value: "South Andaman", label: "South Andaman" },
];

const chandigarhDistricts = [{ value: "Chandigarh", label: "Chandigarh" }];

const dadraNagarHaveliDamanDiuDistricts = [
  { value: "Dadra and Nagar Haveli", label: "Dadra and Nagar Haveli" },
  { value: "Daman", label: "Daman" },
  { value: "Diu", label: "Diu" },
];

const lakshadweepDistricts = [
  { value: "Agatti", label: "Agatti" },
  { value: "Amini", label: "Amini" },
  { value: "Androth", label: "Androth" },
  { value: "Bithra", label: "Bithra" },
  { value: "Chethlath", label: "Chethlath" },
  { value: "Kavaratti", label: "Kavaratti" },
  { value: "Kadmath", label: "Kadmath" },
  { value: "Kalpeni", label: "Kalpeni" },
  { value: "Kilthan", label: "Kilthan" },
  { value: "Minicoy", label: "Minicoy" },
];

const puducherryDistricts = [
  { value: "Karaikal", label: "Karaikal" },
  { value: "Mahe", label: "Mahe" },
  { value: "Puducherry", label: "Puducherry" },
  { value: "Yanam", label: "Yanam" },
];

const ladakhDistricts = [
  { value: "Kargil", label: "Kargil" },
  { value: "Leh", label: "Leh" },
];

const jammuKashmirDistricts = [
  { value: "Anantnag", label: "Anantnag" },
  { value: "Bandipora", label: "Bandipora" },
  { value: "Baramulla", label: "Baramulla" },
  { value: "Budgam", label: "Budgam" },
  { value: "Doda", label: "Doda" },
  { value: "Ganderbal", label: "Ganderbal" },
  { value: "Jammu", label: "Jammu" },
  { value: "Kathua", label: "Kathua" },
  { value: "Kishtwar", label: "Kishtwar" },
  { value: "Kulgam", label: "Kulgam" },
  { value: "Kupwara", label: "Kupwara" },
  { value: "Poonch", label: "Poonch" },
  { value: "Pulwama", label: "Pulwama" },
  { value: "Rajouri", label: "Rajouri" },
  { value: "Ramban", label: "Ramban" },
  { value: "Reasi", label: "Reasi" },
  { value: "Samba", label: "Samba" },
  { value: "Shopian", label: "Shopian" },
  { value: "Srinagar", label: "Srinagar" },
  { value: "Udhampur", label: "Udhampur" },
];

const upDistricts = [
  { value: "Agra", label: "Agra" },
  { value: "Aligarh", label: "Aligarh" },
  { value: "Ambedkar Nagar", label: "Ambedkar Nagar" },
  { value: "Amethi", label: "Amethi" },
  { value: "Amroha", label: "Amroha" },
  { value: "Auraiya", label: "Auraiya" },
  { value: "Ayodhya", label: "Ayodhya" },
  { value: "Azamgarh", label: "Azamgarh" },
  { value: "Badaun", label: "Badaun" },
  { value: "Baghpat", label: "Baghpat" },
  { value: "Bahraich", label: "Bahraich" },
  { value: "Ballia", label: "Ballia" },
  { value: "Balrampur", label: "Balrampur" },
  { value: "Banda", label: "Banda" },
  { value: "Barabanki", label: "Barabanki" },
  { value: "Bareilly", label: "Bareilly" },
  { value: "Basti", label: "Basti" },
  { value: "Bhadohi", label: "Bhadohi" },
  { value: "Bijnor", label: "Bijnor" },
  { value: "Budaun", label: "Budaun" },
  { value: "Bulandshahr", label: "Bulandshahr" },
  { value: "Chandauli", label: "Chandauli" },
  { value: "Chitrakoot", label: "Chitrakoot" },
  { value: "Deoria", label: "Deoria" },
  { value: "Etah", label: "Etah" },
  { value: "Etawah", label: "Etawah" },
  { value: "Farrukhabad", label: "Farrukhabad" },
  { value: "Fatehpur", label: "Fatehpur" },
  { value: "Firozabad", label: "Firozabad" },
  { value: "Gautam Buddha Nagar", label: "Gautam Buddha Nagar" },
  { value: "Ghaziabad", label: "Ghaziabad" },
  { value: "Ghazipur", label: "Ghazipur" },
  { value: "Gonda", label: "Gonda" },
  { value: "Gorakhpur", label: "Gorakhpur" },
  { value: "Hamirpur", label: "Hamirpur" },
  { value: "Hapur", label: "Hapur" },
  { value: "Hardoi", label: "Hardoi" },
  { value: "Hathras", label: "Hathras" },
  { value: "Jalaun", label: "Jalaun" },
  { value: "Jaunpur", label: "Jaunpur" },
  { value: "Jhansi", label: "Jhansi" },
  { value: "Kannauj", label: "Kannauj" },
  { value: "Kanpur Dehat", label: "Kanpur Dehat" },
  { value: "Kanpur Nagar", label: "Kanpur Nagar" },
  { value: "Kasganj", label: "Kasganj" },
  { value: "Kaushambi", label: "Kaushambi" },
  { value: "Kheri", label: "Kheri" },
  { value: "Kushinagar", label: "Kushinagar" },
  { value: "Lalitpur", label: "Lalitpur" },
  { value: "Lucknow", label: "Lucknow" },
  { value: "Maharajganj", label: "Maharajganj" },
  { value: "Mahoba", label: "Mahoba" },
  { value: "Mainpuri", label: "Mainpuri" },
  { value: "Mathura", label: "Mathura" },
  { value: "Mau", label: "Mau" },
  { value: "Meerut", label: "Meerut" },
  { value: "Mirzapur", label: "Mirzapur" },
  { value: "Moradabad", label: "Moradabad" },
  { value: "Muzaffarnagar", label: "Muzaffarnagar" },
  { value: "Pilibhit", label: "Pilibhit" },
  { value: "Pratapgarh", label: "Pratapgarh" },
  { value: "Prayagraj", label: "Prayagraj" },
  { value: "Rae Bareli", label: "Rae Bareli" },
  { value: "Rampur", label: "Rampur" },
  { value: "Saharanpur", label: "Saharanpur" },
  { value: "Sambhal", label: "Sambhal" },
  { value: "Sant Kabir Nagar", label: "Sant Kabir Nagar" },
  { value: "Shahjahanpur", label: "Shahjahanpur" },
  { value: "Shamli", label: "Shamli" },
  { value: "Shravasti", label: "Shravasti" },
  { value: "Siddharthnagar", label: "Siddharthnagar" },
  { value: "Sitapur", label: "Sitapur" },
  { value: "Sonbhadra", label: "Sonbhadra" },
  { value: "Sultanpur", label: "Sultanpur" },
  { value: "Unnao", label: "Unnao" },
  { value: "Varanasi", label: "Varanasi" },
];

const mpDistricts = [
  { value: "Agar Malwa", label: "Agar Malwa" },
  { value: "Alirajpur", label: "Alirajpur" },
  { value: "Anuppur", label: "Anuppur" },
  { value: "Ashoknagar", label: "Ashoknagar" },
  { value: "Balaghat", label: "Balaghat" },
  { value: "Barwani", label: "Barwani" },
  { value: "Betul", label: "Betul" },
  { value: "Bhind", label: "Bhind" },
  { value: "Bhopal", label: "Bhopal" },
  { value: "Burhanpur", label: "Burhanpur" },
  { value: "Chhatarpur", label: "Chhatarpur" },
  { value: "Chhindwara", label: "Chhindwara" },
  { value: "Damoh", label: "Damoh" },
  { value: "Datia", label: "Datia" },
  { value: "Dewas", label: "Dewas" },
  { value: "Dhar", label: "Dhar" },
  { value: "Dindori", label: "Dindori" },
  { value: "Guna", label: "Guna" },
  { value: "Gwalior", label: "Gwalior" },
  { value: "Harda", label: "Harda" },
  { value: "Hoshangabad", label: "Hoshangabad" },
  { value: "Indore", label: "Indore" },
  { value: "Jabalpur", label: "Jabalpur" },
  { value: "Jhabua", label: "Jhabua" },
  { value: "Katni", label: "Katni" },
  { value: "Khandwa", label: "Khandwa" },
  { value: "Khargone", label: "Khargone" },
  { value: "Mandla", label: "Mandla" },
  { value: "Mandsaur", label: "Mandsaur" },
  { value: "Morena", label: "Morena" },
  { value: "Narsinghpur", label: "Narsinghpur" },
  { value: "Neemuch", label: "Neemuch" },
  { value: "Niwari", label: "Niwari" },
  { value: "Panna", label: "Panna" },
  { value: "Raisen", label: "Raisen" },
  { value: "Rajgarh", label: "Rajgarh" },
  { value: "Ratlam", label: "Ratlam" },
  { value: "Rewa", label: "Rewa" },
  { value: "Sagar", label: "Sagar" },
  { value: "Satna", label: "Satna" },
  { value: "Sehore", label: "Sehore" },
  { value: "Seoni", label: "Seoni" },
  { value: "Shahdol", label: "Shahdol" },
  { value: "Shajapur", label: "Shajapur" },
  { value: "Sheopur", label: "Sheopur" },
  { value: "Shivpuri", label: "Shivpuri" },
  { value: "Sidhi", label: "Sidhi" },
  { value: "Singrauli", label: "Singrauli" },
  { value: "Tikamgarh", label: "Tikamgarh" },
  { value: "Ujjain", label: "Ujjain" },
  { value: "Umaria", label: "Umaria" },
  { value: "Vidisha", label: "Vidisha" },
];

const rajasthanDistricts = [
  { value: "Ajmer", label: "Ajmer" },
  { value: "Alwar", label: "Alwar" },
  { value: "Banswara", label: "Banswara" },
  { value: "Baran", label: "Baran" },
  { value: "Barmer", label: "Barmer" },
  { value: "Bharatpur", label: "Bharatpur" },
  { value: "Bhilwara", label: "Bhilwara" },
  { value: "Bikaner", label: "Bikaner" },
  { value: "Bundi", label: "Bundi" },
  { value: "Chittorgarh", label: "Chittorgarh" },
  { value: "Churu", label: "Churu" },
  { value: "Dausa", label: "Dausa" },
  { value: "Dholpur", label: "Dholpur" },
  { value: "Dungarpur", label: "Dungarpur" },
  { value: "Hanumangarh", label: "Hanumangarh" },
  { value: "Jaipur", label: "Jaipur" },
  { value: "Jaisalmer", label: "Jaisalmer" },
  { value: "Jalore", label: "Jalore" },
  { value: "Jhalawar", label: "Jhalawar" },
  { value: "Jhunjhunu", label: "Jhunjhunu" },
  { value: "Jodhpur", label: "Jodhpur" },
  { value: "Karauli", label: "Karauli" },
  { value: "Kota", label: "Kota" },
  { value: "Nagaur", label: "Nagaur" },
  { value: "Pali", label: "Pali" },
  { value: "Pratapgarh", label: "Pratapgarh" },
  { value: "Rajsamand", label: "Rajsamand" },
  { value: "Sawai Madhopur", label: "Sawai Madhopur" },
  { value: "Sikar", label: "Sikar" },
  { value: "Sirohi", label: "Sirohi" },
  { value: "Sri Ganganagar", label: "Sri Ganganagar" },
  { value: "Tonk", label: "Tonk" },
  { value: "Udaipur", label: "Udaipur" },
];

export {
  indianStates,
  upDistricts,
  mpDistricts,
  rajasthanDistricts,
  andhraPradeshDistricts,
  arunachalPradeshDistricts,
  assamDistricts,
  biharDistricts,
  chhattisgarhDistricts,
  goaDistricts,
  gujaratDistricts,
  haryanaDistricts,
  himachalPradeshDistricts,
  jharkhandDistricts,
  karnatakaDistricts,
  keralaDistricts,
  maharashtraDistricts,
  manipurDistricts,
  meghalayaDistricts,
  mizoramDistricts,
  nagalandDistricts,
  punjabDistricts,
  odishaDistricts,
  sikkimDistricts,
  tamilNaduDistricts,
  telanganaDistricts,
  tripuraDistricts,
  uttarakhandDistricts,
  westBengalDistricts,
  andamanNicobarDistricts,
  chandigarhDistricts,
  dadraNagarHaveliDamanDiuDistricts,
  lakshadweepDistricts,
  puducherryDistricts,
  ladakhDistricts,
  jammuKashmirDistricts,
};
